language: node_js
node_js:
    - 8

notifications:
  email: false

cache:
  directories:
    - "node_modules"

jobs:
    include:
        - stage: branch test
          script: npm test && npm run build
        - stage: npm publish
          script: npm test && npm run build
          after_success: npm run semantic-release

stages:
  - name: branch test
    if: branch != master
  - name: npm publish
    if: branch = master
